DefaultContentLanguage = "id"
RemovePathAccents = true
baseURL = "https://financetest-by.netlify.app"
canonifyURLs = true
disqusShortname = "halimboi"
enableRobotsTXT = true
googleAnalytics = "UA-155099144-3"
languageCode = "id-ID"
paginate = 5
theme = "less"
timeout = 200000
title = "financetest-by.com"


[author]
name = "Brad Yuly"
[blackfriday]
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true
[imaging]
resampleFilter = "lanczos"


[[menu.main]]
name = "Finance 101"
url = "/finance 101"
weight = 1

[[menu.main]]
identifier = "terminal"
name = "Budgeting"
title = "Manage money so you can do what you want."
url = "/budgeting"
weight = 2

[[menu.main]]
identifier = "retirement"
name = "Retirement"
title = "Get to the finish line."
url = "/retirement"
weight = 3



[[menu.main]]
identifier = "desktop"
name = "Placeholder"
title = "currently not used...but might in the future."
url = "/desktop"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
title = "Who I am."
url = "/about"
weight = 5


[params]
accentColor = "#00bcd4"
bodyFont = "Lora"
copyright = "Bradley Yuly"
hasLogo = true
heroHeader = true
sansSerifFont = "Josefin Sans"
sizes = ["2048", "1024", "512"]
tags = []
titleFont = "Crimson Text"


[params.license]
type = "CC BY-NC 4.0"
url = "/cc-by-nc"
[params.policy]
type = "Privacy Policy"
url = "/policy"

[params.social]
domain = "Bradley Yuly"
email = "brad.yuly@protonmail.com"
linkedin = "doni-halim-16a6ba1a0"
paypal = "bryuly"
#	twitter = "halimboi"

[params.titles]
categories = "Topics"
posts = "Finance 101"
[permalinks]
categories = "/:slug"
posts = "/:slug"
[[related.indices]]
includeNewer = true
name = "categories"
weight = 1
[taxonomies]
category = "categories"
