baseURL = "https://financetest-by.netlify.app"
languageCode = "id-ID"
DefaultContentLanguage = "id"
title = "financetest-by.com"
theme = "less"
timeout = 200000
RemovePathAccents = true
enableRobotsTXT = true
canonifyURLs = true
#number of pages listed at bottom of page??
paginate = 2
googleAnalytics = "UA-155099144-3"
disqusShortname = "Bradley"

[author]
  name = "Bradley Yuly"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[permalinks]
  posts = "/:slug"
  categories = "/:slug"

[imaging]
  resampleFilter = "lanczos"

[params]
  #googleAdsense = "ca-pub-3520097993586116"
  copyright = "Bradley Yuly"

  # image size
  sizes = [ "2048" , "1024" , "512" ]
  tags = []

  # fonts
  sansSerifFont = "Josefin Sans"
  titleFont = "Crimson Text"
  bodyFont = "Lora"

  # color
  accentColor = "#00bcd4"
  hasLogo = true
  heroHeader = true

[taxonomies]
  category = "categories"

[params.titles]
  posts = "Finance 101"
  categories = "Topics"

# social
[params.social]
  email = "brad.yuly@protonmail.com"
  domain = "Bradley Yuly"
  instagram = "instagram name here"
  twitter = "twitter name here"
  facebook = "facebook name here"
  linkedin = "linkedin name and number here"
  github = "username here"
  paypal = "name here"
  telegram = "name here"

# menu contents
[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	identifier = "terminal"
	name = "Budgeting"
	title = "Manage money so you can do what you want."
	url = "/budgeting"
	weight = 2
[[menu.main]]
	identifier = "retirement"
	name = "Retirement"
	title = "Get to the finish line."
	url = "/retirement"
	weight = 3
[[menu.main]]
	identifier = "finance 101"
	name = "Finance 101"
	title = "Learn some terminology, concepts, and more."
	url = "/desktop"
	weight = 4
[[menu.main]]
	identifier = "about"
	name = "About"
	title = "Who I am."
	url = "/about"
	weight = 5

# footer contents
[params.license]
  type = "Use License"
  url = "/cc-by-nc"

[params.policy]
  type = "Privacy Policy"
  url = "/policy"

[[related.indices]]
  name = "categories"
  weight =  1
  includeNewer = true